# Routes
ROUTE_HOME = "/"
ROUTE_CHAT = "/chat"

# API URLs
OPENROUTER_API_URL = "https://openrouter.ai/api/v1/chat/completions"

# Models
OPENROUTER_MODEL_FREE = "openai/gpt-oss-20b:free"

# Error messages
ERROR_NO_API_KEY = "Server configuration error: OPENROUTER_API_KEY is missing."
ERROR_INVALID_JSON = "Invalid or missing JSON in request"
ERROR_NO_MESSAGE = "No message provided"
ERROR_NO_CONTENT = "No content generated by the model."
ERROR_TIMEOUT = "Request to AI service timed out"
ERROR_NON_JSON = "OpenRouter returned a non-JSON error page."
